---
- name: "Notify: install role started"
  ansible.builtin.debug:
    msg: "Notify: install role started"

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  tags: apt-fast-install
  ignore_errors: true
  register: install_result

- name: "Install apt-fast package"
  ansible.builtin.apt:
    name: "{{ apt_fast.packages }}"
    state: present
  tags: apt-fast-install
  register: apt_install_result
  ignore_errors: true
  when: install_result is not failed

- name: "Notify: install role finished"
  ansible.builtin.debug:
    msg: "Notify: install role finished"
  when: install_result is not failed and apt_install_result is not failed

- name: "Notify: install role finished with failure"
  ansible.builtin.debug:
    msg: "Notify: install role finished with failure"
  when: install_result is failed and apt_install_result is failed
