---
- name: "Notify: telegram role started"
  ansible.builtin.debug:
    msg: "Notify: telegram role started"

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ telegram_dependencies }}"
  become: true

- name: "Notify: dependencies installed"
  ansible.builtin.debug:
    msg: "Notify: dependencies installed."

- name: Download Telegram
  ansible.builtin.get_url:
    url: "{{ telegram_download_url }}"
    dest: "/tmp/telegram.tar.xz"
    mode: '0664'
  become: true

- name: "Notify: telegram downloaded"
  ansible.builtin.debug:
    msg: "Notify: telegram downloaded."

- name: Unpack Telegram
  ansible.builtin.unarchive:
    src: /tmp/telegram.tar.xz
    dest: /opt/
    remote_src: true
  become: true

- name: "Notify: telegram unpacked"
  ansible.builtin.debug:
    msg: "Notify: telegram unpacked."

- name: Remove Telegram archive
  ansible.builtin.file:
    path: /tmp/telegram.tar.xz
    state: absent
  become: true

- name: "Notify: telegram archive removed"
  ansible.builtin.debug:
    msg: "Notify: telegram archive removed."

- name: Configure Telegram
  ansible.builtin.file:
    src: /opt/Telegram/Telegram
    dest: /usr/bin/telegram
    state: link
  become: true

- name: "Notify: telegram Configured"
  ansible.builtin.debug:
    msg: "Notify: telegram Configured"
