---
- name: "Notify: alias role started"
  debug:
    msg: "Notify: alias role started"

- name: Настраиваем алиасы для всех пользователей
  include_tasks: setup_aliases.yml
  register: setup_aliases_result
  ignore_errors: true

- name: Настраиваем ZSH (если включено)
  include_tasks: setup_zsh.yml
  when: enable_zsh
  register: setup_zsh_result
  ignore_errors: true

- name: "Notify: alias role finished"
  debug:
    msg: "Notify: alias role finished"
  when: setup_aliases_result is not failed and setup_zsh_result is not failed

- name: "Notify: alias role finished with failure"
  debug:
    msg: "Notify: alias role finished with failure"
  when: setup_aliases_result is failed or setup_zsh_result is failed