---
- name: "Notify: virtualbox role started"
  debug:
    msg: "Notify: virtualbox role started"

- include_tasks: install_dependencies.yml
- include_tasks: add_repository.yml
- include_tasks: install_packages.yml
- include_tasks: configure_virtualbox.yml
- include_tasks: install_extension.yml
  when: install_extension_pack | bool

- name: "Notify: virtualbox role finished"
  debug:
    msg: "Notify: virtualbox role finished"