---
- name: Append vboxusers group
  ansible.builtin.user:
    name: "{{ virtualbox_ansible_user_id }}"
    groups: vboxusers
    append: yes

- name: "Notify: vboxusers appended"
  ansible.builtin.debug:
    msg: "Notify: vboxusers appended."

- name: Init VirtualBox
  ansible.builtin.service:
    name: vboxdrv
    state: started
    enabled: yes
