---
- name: Download Extension Pack
  get_url:
    url: "{{ extension.url }}"
    dest: "{{ extension.path }}"
    mode: "0644"

- name: Install Extension Pack
  community.general.virtualbox_extension_pack:
    name: "{{ extension.name }}"
    path: "{{ extension.path }}"
    state: present
    virtualbox_path: /usr/bin/virtualbox

- name: "Notify: extension Pack installed"
  debug:
    msg: "Notify: extension Pack installed."