---
- name: "Notify: vscode role started"
  ansible.builtin.debug:
    msg: "Notify: vscode role started"

- name: Install dependencies
  ansible.builtin.include_tasks: install_dependencies.yml
  register: install_dependencies_result
  ignore_errors: true

- name: Install VSCode
  ansible.builtin.include_tasks: install_vscode.yml
  register: install_vscode_result
  when: install_dependencies_result is not failed
  ignore_errors: true

- name: Configure VSCode
  ansible.builtin.include_tasks: configure_vscode.yml
  register: configure_vscode_result
  when: install_vscode_result is not failed
  ignore_errors: true

- name: Install extensions
  ansible.builtin.include_tasks: install_extensions.yml
  register: install_extensions_result
  when: install_vscode_result is not failed
  ignore_errors: true

- name: Set task status
  ansible.builtin.set_fact:
    vscode_tasks_status: "{{ install_dependencies_result is not failed and install_vscode_result is not failed and install_extensions_result is not failed }}"

- name: "Notify: drawio role finished"
  ansible.builtin.debug:
    msg: >-
      Notify: drawio role finished
      {% if not vscode_tasks_status %} with failure{% endif %}
