---
- name: "Notify: drivers role started"
  ansible.builtin.debug:
    msg: "Notify: drivers role started"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "Notify: apt cache updated"
  ansible.builtin.debug:
    msg: "Notify: apt cache updated."

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: "Notify: apt cache upgraded"
  ansible.builtin.debug:
    msg: "Notify: apt cache upgraded"

- name: Ubuntu drivers autoinstall
  ansible.builtin.command: ubuntu-drivers autoinstall
  register: ubuntu_drivers
  changed_when: false
  become: true

- name: "Notify: drivers installed"
  ansible.builtin.debug:
    msg: "Notify: drivers installed."

- name: "Notify: drivers role finished"
  ansible.builtin.debug:
    msg: "Notify: drivers role finished"
