---
- name: "Notify: nemo role started"
  debug:
    msg: "Notify: nemo role started"

- name: Install Nemo
  apt:
    name: nemo
    state: present
    install_recommends: no

- name: "Notify: nemo installed"
  debug:
    msg: "Notify: nemo installed."

- name: Remove nautilus
  block:
  - name: Remove Nautilus
    become: true
    apt:
      name: nautilus
      state: absent
      purge: yes

  - name: Autoremove unused packages
    become: true
    apt:
      autoremove: yes

- name: "Notify: Nautilus removed"
  debug:
    msg: "Notify: Nautilus removed."

- name: Configure Nemo as default file manager
  block:
    - name: Install xdg-utils
      apt:
        name: xdg-utils
        state: present
        install_recommends: no

    - name: Set Nemo as default file manager
      command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
      become: true

    - name: Disable GNOME desktop icons
      command: gsettings set org.gnome.desktop.background show-desktop-icons false
      become: true

    - name: Enable Nemo desktop icons
      command: gsettings set org.nemo.desktop show-desktop-icons true
      become: true
  become: true

- name: "Notify: nemo Configured"
  debug:
    msg: "Notify: nemo Configured"

- name: "Notify: nemo role finished"
  debug:
    msg: "Notify: nemo role finished"