---
- name: "Notify: nemo role started"
  debug:
    msg: "Notify: nemo role started"

- name: Install Nemo
  apt:
    name: nemo
    state: present
    upgrade: dist
    install_recommends: no

- name: "Notify: nemo installed"
  debug:
    msg: "Notify: nemo installed."

- name: Configure Nemo as default file manager
  block:
    - name: Set Nemo as default file manager
      command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
      become: true

    - name: Disable GNOME desktop icons
      command: gsettings set org.gnome.desktop.background show-desktop-icons false
      become: true

    - name: Enable Nemo desktop icons
      command: gsettings set org.nemo.desktop show-desktop-icons true
      become: true
  become: true

- name: "Notify: nemo Configured"
  debug:
    msg: "Notify: nemo Configured"

- name: "Notify: nemo role finished"
  debug:
    msg: "Notify: nemo role finished"