---
- name: Install VirtualBox
  ansible.builtin.apt:
    name: "{{ virtualbox_packages }}"
    state: present

- name: "Notify: VirtualBox installed"
  ansible.builtin.debug:
    msg: "Notify: VirtualBox installed."
